language:
  - cpp

compiler:
  - gcc
  - clang

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - lcov
      - mesa-common-dev

before_install:
  # C++14, even C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y mesa-common-dev
  - sudo apt-get install -y libgl1-mesa-dev

install: 
  # C++14, even C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  #- pip install codecov


script:
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug
  # Run test
  - valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./../bin/guise_tests

after_success:
  - lcov --directory ./CMakeFiles/guise.dir --capture --output-file coverage.info #Or remove '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
